### ISSUE TITLE
Unclear how to achieve parallelization in git annex v6

### ISSUE THREAD

**Issue by mih** [datalad/datalad-revolution#10]
Most of the works git annex does is happening after actually calling git (e.g. `git add`). How could be instruct git annex to use multiple workers in this case?

**Comment by yarikoptic** [comment]
Does git support multiple workers without failing? (locking)

**Comment by mih** [comment]
Does it?

**Comment by mih** [comment]
The answer to the original question is that there can be no change to the parallelization setup and exclusively using the Git API implies not having parallelization: https://git-annex.branchable.com/devblog/day_550__a_plan_to_finish_v6/
