### ISSUE TITLE
setup.py needs tuning for older systems

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-revolution#66]
I believe it is the

```
'pathlib2; python_version < "3.0"',
```
which makes nd80 puke (http://smaug.datalad.org:8020/builders/datalad-pr-docker-dl-nd80/builds/4839)

```
    error in datalad setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
```

I guess the best would be to condition on setuptools version, after figuring out which is needed; and otherwise just do it for `sys.version_info[0] < 3`

**Comment by mih** [comment]
Hmm, Debian 8.0 has passed it's end-of-life in July this year -- maybe it is time to let it go?

**Comment by yarikoptic** [comment]
ah, indeed
