### ISSUE TITLE
git annex findref approach to obtain annex branch info is insufficient

### ISSUE THREAD

**Issue by mih** [datalad/datalad-revolution#68]
`git annex findref HEAD~2` will only report on files that where under annex control at state `HEAD~2` **AND** when that content is still present in the local annex. We need a different approach .

Most of the info that can be seen in https://github.com/datalad/datalad/issues/2160#issuecomment-448151451 can be computed directly from the key on record for a `ref`.

**Comment by kyleam** [comment]
> `git annex findref HEAD~2` will only report on files that where under annex control at state `HEAD~2` **AND** when that content is still present in the local annex

I suppose with `find`, you'd use `--include=*` to get all the files.  I was hoping that'd work with `findref` too.  It looks like the issue is that `findref` uses `nonWorkTreeMatchingOptions`, which means it doesn't recognize `--include=*`.  That's unfortunate because, when `--include=*` means "list all annex files", it's not really tied to the working tree.

As a workaround, what about making two calls?

```
git annex findref --json <ref>
git annex findref --json --not --in=here <ref>
```

**Comment by mih** [comment]
Thanks for pointing that out. This sounds like a good compromise.

**Comment by mih** [comment]
Looked into this now, and the `--not --in=here` still isn't sufficient, as it depends in the local repo to have knowledge of that key being available in at least one other annex, i.e. if I just have it locally, and `rm` it, neither command will report on any file that references this key.

**Comment by mih** [comment]
Seems like the desired effect can be "achieved" via `git annex findref HEAD --copies 0 --json`

**Comment by kyleam** [comment]
>  `--not --in=here` still isn't sufficient, as it depends in the local repo to have knowledge of that key being available in at least one other annex

I see.



> Seems like the desired effect can be "achieved" via `git annex findref HEAD --copies 0 --json`

Nice.
